AYKIRI GÖZLEM ANALİZİ

TEK BOYUTLU

In [ ]:
import seaborn as sns

df = sns.load_dataset("diamonds")
df = df.select_dtypes(include=["float64", "int64"])
df = df.dropna()
df.head()

In [ ]:
df_table = df["table"]

In [ ]:
df_table.head()

In [ ]:
sns.boxplot(x=df_table)

In [ ]:
Q1 = df_table.quantile(0.25)
Q3 = df_table.quantile(0.75)
IQR = Q3 - Q1

In [ ]:
Q1

In [ ]:
Q3

In [ ]:
IQR

In [ ]:
alt_sinir = Q1 - 1.5 * IQR  ## eşik değeri
ust_sinir = Q3 + 1.5 * IQR

In [ ]:
alt_sinir

In [ ]:
ust_sinir

In [ ]:
((df_table < alt_sinir) | (df_table > ust_sinir))

In [ ]:
aykiri_tf = (df_table < alt_sinir)

In [ ]:
aykiri_tf.head()

In [ ]:
df_table[aykiri_tf]

In [ ]:
df_table[aykiri_tf].index

SİLME

In [ ]:
import pandas as pd

In [ ]:
type(df_table)

In [ ]:
df_table = pd.DataFrame(df_table)

In [ ]:
df_table.shape

In [ ]:
t_df = df_table[~((df_table < (alt_sinir)) | (df_table > (ust_sinir))).any(axis=1)]  # aykirilarin dışındakileri getir

In [ ]:
t_df.shape

ORTALAMA İLE DOLDURMA

In [ ]:
df = sns.load_dataset("diamonds")
df = df.select_dtypes(include=["float64", "int64"])
df = df.dropna()
df.head()

In [ ]:
df_table = df["table"]

In [ ]:
aykiri_tf.head()

In [ ]:
df_table[aykiri_tf]

In [ ]:
df_table.mean()

In [ ]:
df_table[aykiri_tf] = df_table.mean()

In [ ]:
df_table[aykiri_tf]

Baskılama Yöntemi

In [ ]:
df = sns.load_dataset("diamonds")
df = df.select_dtypes(include=["float64", "int64"])
df = df.dropna()
df.head()

In [ ]:
df_table = df["table"]

In [ ]:
df_table[aykiri_tf]

In [ ]:
alt_sinir

In [ ]:
df_table[aykiri_tf] = alt_sinir

In [ ]:
df_table[aykiri_tf]

ÇOK DEGİSKENLİ AYKIRI DEGER ANALİZİ

LOCAL OUTLİER FACTOR (LOF)

Komşu yoğunluğuna göre

In [ ]:
df = sns.load_dataset("diamonds")
df = df.select_dtypes(include=["float64", "int64"])
df = df.dropna()
df.head()

In [ ]:
import numpy as np

In [ ]:
from sklearn.neighbors import LocalOutlierFactor

In [ ]:
clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)

In [ ]:
clf.fit_predict(df)

In [ ]:
df_scores = clf.negative_outlier_factor_

In [ ]:
df_scores[0:10]

In [ ]:
np.sort(df_scores)[0:20]

In [ ]:
np.sort(df_scores)[13]

In [ ]:
esik_deger = np.sort(df_scores)[13]

In [ ]:
aykiri_tf = df_scores > esik_deger

In [ ]:
aykiri_tf

SİLME YÖNTEMİ

In [ ]:
yeni_df = df[df_scores > esik_deger]

In [ ]:
yeni_df  # aykiri olmayan değerler

In [ ]:
df[df_scores < esik_deger]

BASKILAMA YÖNTEMİ

In [ ]:
df[df_scores == esik_deger]

In [ ]:
baski_degeri = df[df_scores == esik_deger]

In [ ]:
aykirilar = df[~aykiri_tf]

In [ ]:
aykirilar.to_records(index=False)

In [ ]:
res = aykirilar.to_records(index=False)

In [ ]:
res[:] = baski_degeri.to_records(index=False)

In [ ]:
res

In [ ]:
df[~aykiri_tf]

In [ ]:
df[~aykiri_tf] = pd.DataFrame(res, index=df[~aykiri_tf].index)

In [ ]:
df[aykiri_tf]

EKSİK VERİ
1-Eksiklik yapısal mı?
2-Her zaman eksiklik anlamına gelmez
3-Bilgi kaybı

In [ ]:
import numpy as np
import pandas as pd

v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
v2 = np.array([7, np.NAN, 5, 8, 12, np.NAN, np.NAN, 2, 3])
v3 = np.array([np.NAN, 12, 5, 6, 14, 7, np.NAN, 2, 31])
df = pd.DataFrame(
    {"v1": v1,
     "v2": v2,
     "v3": v3
     })

df

In [ ]:
df.isnull().sum()

In [ ]:
df.notnull().sum()

In [ ]:
df.isnull().sum().sum()

In [ ]:
df.isnull()

In [ ]:
df[df.isnull().any(axis=1)]

In [ ]:
df[df.notnull().all(axis=1)]

In [ ]:
df[df["v1"].notnull() & df["v2"].notnull() & df["v3"].notnull()]

EKSİK DEGERLERİN GİDERİLMESİ

In [ ]:
df.dropna()  # inplace: kalıcı yapar

In [ ]:
df

BASİT DEGER ATAMA

In [ ]:
df["v1"].mean()

In [ ]:
df["v1"].fillna(df["v1"].mean())

In [ ]:
v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
df

In [ ]:
v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
v2 = np.array([7, np.NAN, 5, 8, 12, np.NAN, np.NAN, 2, 3])
v3 = np.array([np.NAN, 12, 5, 6, 14, 7, np.NAN, 2, 31])
df = pd.DataFrame(
    {"v1": v1,
     "v2": v2,
     "v3": v3
     })

df

In [ ]:
df.apply(lambda x: x.fillna(x.mean()), axis=0)

EKSİK VERİ YAPISININ GÖRSELLEŞTİRİLMESİ

In [ ]:
import missingno as msno

In [ ]:
msno.bar(df);

In [ ]:
msno.matrix(df);

In [ ]:
import seaborn as sns

df = sns.load_dataset("planets")
df.head()

In [ ]:
df.isnull().sum()

In [ ]:
msno.matrix(df);

In [ ]:
msno.heatmap(df);

SAYISAL DEGİSKENLERDE ATAMA

In [ ]:
import numpy as np
import pandas as pd

v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
v2 = np.array([7, np.NAN, 5, 8, 12, np.NAN, np.NAN, 2, 3])
v3 = np.array([np.NAN, 12, 5, 6, 14, 7, np.NAN, 2, 31])
df = pd.DataFrame(
    {"v1": v1,
     "v2": v2,
     "v3": v3
     })

df

In [ ]:
df.fillna(df.mean()[:])

In [ ]:
df.fillna(df.mean()["v1":"v2"])

In [ ]:
df["v3"].fillna(df["v3"].median())

In [ ]:
df.where(pd.notna(df), df.mean(), axis="columns")

KATEGORİK DEĞİSKEN KIRILIMINDA DEGER ATAMA

In [ ]:
v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
v2 = np.array([7, np.NAN, 5, 8, 12, np.NAN, np.NAN, 2, 3])
v3 = np.array([np.NAN, 12, 5, 6, 14, 7, np.NAN, 2, 31])
v4 = np.array(["IT", "IT", "IK", "IK", "IK", "IK", "IK", "IT", "IT", ])

df = pd.DataFrame({
    "maas": v1,
    "v2": v2,
    "v3": v3,
    "departman": v4
})

df

In [ ]:
df.groupby("departman")["maas"].mean()

In [ ]:
df["maas"].fillna(df.groupby("departman")["maas"].transform("mean"))

KATEGORİK DEGİSKENLER İÇİN EKSİK DEGER ATAMA

In [ ]:
import numpy as np
import pandas as pd

v1 = np.array([1, 3, 6, np.NAN, 7, 1, np.NAN, 9, 15])
v4 = np.array(["IT", np.NAN, "IK", "IK", "IK", "IK", "IK", "IT", "IT"], dtype=object)

df = pd.DataFrame({
    "maas": v1,
    "departman": v4
})

df

In [ ]:
df["departman"].fillna(df["departman"].mode()[0])

In [ ]:
df

In [ ]:
df["departman"].fillna(method="bfill")

In [ ]:
df["departman"].fillna(method="ffill")

TAHMİNE DAYALI DEĞER ATAMA YÖNTEMLERİ

In [8]:
import seaborn as sns
import missingno as msno

df = sns.load_dataset("titanic")
df = df.select_dtypes(include=["float64", "int64"])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [13]:
from ycimpute.imputer import knnimput

In [14]:
var_names = list(df)

In [15]:
n_df = np.array(df)

In [16]:
n_df[0:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [18]:
n_df.shape

(891, 6)

In [19]:
dff = knnimput.KNN(k=4).complete(n_df)

Imputing row 1/891 with 0 missing, elapsed time: 0.178
Imputing row 101/891 with 0 missing, elapsed time: 0.180
Imputing row 201/891 with 0 missing, elapsed time: 0.181
Imputing row 301/891 with 1 missing, elapsed time: 0.182
Imputing row 401/891 with 0 missing, elapsed time: 0.183
Imputing row 501/891 with 0 missing, elapsed time: 0.184
Imputing row 601/891 with 0 missing, elapsed time: 0.185
Imputing row 701/891 with 0 missing, elapsed time: 0.186
Imputing row 801/891 with 0 missing, elapsed time: 0.187


In [22]:
dff = pd.DataFrame(dff, columns=var_names)
dff

survived  pclass        age  sibsp  parch     fare
0         0.0     3.0  22.000000    1.0    0.0   7.2500
1         1.0     1.0  38.000000    1.0    0.0  71.2833
2         1.0     3.0  26.000000    0.0    0.0   7.9250
3         1.0     1.0  35.000000    1.0    0.0  53.1000
4         0.0     3.0  35.000000    0.0    0.0   8.0500
..        ...     ...        ...    ...    ...      ...
886       0.0     2.0  27.000000    0.0    0.0  13.0000
887       1.0     1.0  19.000000    0.0    0.0  30.0000
888       0.0     3.0  26.026414    1.0    2.0  23.4500
889       1.0     1.0  26.000000    0.0    0.0  30.0000
890       0.0     3.0  32.000000    0.0    0.0   7.7500

[891 rows x 6 columns]

In [23]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

In [24]:
df = sns.load_dataset("titanic")
df = df.select_dtypes(include=["float64", "int64"])
df.isnull().sum()

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [25]:
df.isnull().sum()

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [26]:
var_names = list(df)

In [27]:
n_df = np.array(df)

In [32]:
from ycimpute.imputer import iterforest

dff = iterforest.IterImput().complete(n_df)

AttributeError: module 'ycimpute.imputer.iterforest' has no attribute 'IterImput'

In [29]:
dff = pd.DataFrame(dff, columns=var_names)

In [34]:
df.isnull().sum()

survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

EM YÖNTEMİ İLEDE YAPILABİLİR

DEGİSKEN STANDARTİZASYONU

In [35]:

v1 = np.array([1, 3, 6, 5, 7])
v2 = np.array([7, 7, 5, 8, 12])
v3 = np.array([6, 12, 5, 6, 14])
df = pd.DataFrame(
    {"v1": v1,
     "v2": v2,
     "v3": v3
     })
df = df.astype(float)
df

v1    v2    v3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [37]:
# Standardizasyon
from sklearn import preprocessing

In [38]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [39]:
df

v1    v2    v3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [40]:
df.mean()

v1    4.4
v2    7.8
v3    8.6
dtype: float64

In [42]:
# Normalizasyon
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

In [47]:
scaler = preprocessing.MinMaxScaler(feature_range=(10, 20))

In [48]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

In [49]:
import seaborn as sns

df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 0-1 Dönüşümü

In [52]:
from sklearn.preprocessing import LabelEncoder

lbe = LabelEncoder()

In [53]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [54]:
df["yeni_sex"] = lbe.fit_transform(df["sex"])

In [55]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

In [56]:
# 1 ve Diğerleri dönüşümü
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [64]:
import numpy as no

df["yeni_day"] = np.where(df["day"].str.contains("Sun"), 1, 0)


In [67]:
# Çok sınıflı dönüşüm

lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

ONE-HOT DÖNÜŞÜMÜ ve DUMMY DEĞİŞKEN TUZAĞI

In [68]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0         1

In [70]:
pd.get_dummies(df, columns=["sex"], prefix=["sex"])

total_bill   tip smoker   day    time  size  yeni_sex  yeni_day   
0         16.99  1.01     No   Sun  Dinner     2         0         1  \
1         10.34  1.66     No   Sun  Dinner     3         1         1   
2         21.01  3.50     No   Sun  Dinner     3         1         1   
3         23.68  3.31     No   Sun  Dinner     2         1         1   
4         24.59  3.61     No   Sun  Dinner     4         0         1   
..          ...   ...    ...   ...     ...   ...       ...       ...   
239       29.03  5.92     No   Sat  Dinner     3         1         0   
240       27.18  2.00    Yes   Sat  Dinner     2         0         0   
241       22.67  2.00    Yes   Sat  Dinner     2         1         0   
242       17.82  1.75     No   Sat  Dinner     2         1         0   
243       18.78  3.00     No  Thur  Dinner     2         0         0   

     sex_Male  sex_Female  
0       False        True  
1        True       False  
2        True       False  
3        True       False  
4       False        True  
..        ...         ...  
239      True       False  
240     False        True  
241      True       False  
242      True       False  
243     False        True  

[244 rows x 10 columns]

In [72]:
pd.get_dummies(df, columns=["day"], prefix=["day"]).head()

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day   
0       16.99  1.01  Female     No  Dinner     2         0         1  \
1       10.34  1.66    Male     No  Dinner     3         1         1   
2       21.01  3.50    Male     No  Dinner     3         1         1   
3       23.68  3.31    Male     No  Dinner     2         1         1   
4       24.59  3.61  Female     No  Dinner     4         0         1   

   day_Thur  day_Fri  day_Sat  day_Sun  
0     False    False    False     True  
1     False    False    False     True  
2     False    False    False     True  
3     False    False    False     True  
4     False    False    False     True