In [24]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])

ab

In [33]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a * b

In [26]:
a = np.array([1, 2, 3, 4, 5])
type(a)

In [27]:
np.array([3.14, 4, 2, 13], dtype="int")

In [28]:
# sifirdan array oluşturma

np.zeros(10, dtype="int")

In [31]:
np.ones((3, 5), dtype=int)

In [1]:
import numpy as np

np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [2]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [3]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [4]:
np.random.normal(10, 4, (3, 4))

array([[ 8.68925626, 13.41969555, 14.72831347,  6.85104259],
       [15.12195513, 14.12388129, 14.14774858,  6.94809675],
       [ 6.63638608,  7.22636163,  8.94544659, 12.49551038]])

In [5]:
np.random.randint(0, 10, (3, 3))

array([[7, 0, 8],
       [9, 1, 5],
       [3, 8, 8]])

In [8]:
np.random.randint(10, size=10)

array([7, 8, 1, 8, 7, 6, 6, 0, 4, 7])

In [10]:
a = np.random.randint(10, size=10)

In [11]:
a.ndim

1

In [12]:
a.shape

(10,)

In [13]:
a.size

10

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.random.randint(10, size=(3, 5))

In [16]:
b

array([[1, 8, 9, 6, 6],
       [0, 1, 6, 4, 1],
       [7, 0, 8, 1, 7]])

In [20]:
b.ndim

2

In [21]:
b.size

15

In [23]:
b.shape

(3, 5)

In [24]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a = np.arange(1, 10)

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a.ndim

1

In [34]:
b = a.reshape((1, 9))

In [35]:
b.ndim

2

In [36]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [38]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [39]:
z = np.array([7, 8, 9])

In [40]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# iki boyut

In [49]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [52]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [54]:
np.split(x, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [56]:
a, b, c = np.split(x, [3, 5])

In [57]:
a

array([1, 2, 3])

In [59]:
c

array([3, 2, 1])

In [58]:
b

array([99, 99])

In [60]:
m = np.arange(16).reshape(4, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
ust, alt = np.vsplit(m, [2])

In [64]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [66]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [69]:
v = np.array([2, 1, 4, 3, 5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [71]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [72]:
v.sort()

In [73]:
v

array([1, 2, 3, 4, 5])

In [76]:
m = np.random.normal(20, 5, [3, 3])

In [77]:
m

array([[25.14420013, 26.83664113, 24.80731706],
       [23.63274302, 31.97177638, 13.72443855],
       [21.72683317, 18.03643319, 19.84977824]])

In [78]:
np.sort(m, axis=1)

array([[24.80731706, 25.14420013, 26.83664113],
       [13.72443855, 23.63274302, 31.97177638],
       [18.03643319, 19.84977824, 21.72683317]])

In [79]:
np.sort(m, axis=0)

array([[21.72683317, 18.03643319, 13.72443855],
       [23.63274302, 26.83664113, 19.84977824],
       [25.14420013, 31.97177638, 24.80731706]])

In [81]:
a = np.random.randint(10, size=10)
a

array([7, 7, 3, 3, 2, 9, 8, 0, 8, 5])

In [82]:
a[0]

7

In [84]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
a[0:3]

array([20, 21, 22])

In [87]:
a = np.random.randint(10, size=(5, 5))
a

array([[8, 1, 0, 9, 7],
       [9, 1, 1, 6, 7],
       [9, 0, 4, 2, 2],
       [9, 8, 6, 9, 5],
       [0, 1, 9, 7, 4]])

In [90]:
alt_a = a[0:3, 0:2]
alt_a

array([[8, 1],
       [9, 1],
       [9, 0]])

In [92]:
alt_a[0, 0] = 99999
alt_a[1, 1] = 888

In [93]:
alt_a

array([[99999,     1],
       [    9,   888],
       [    9,     0]])

In [94]:
a

array([[99999,     1,     0,     9,     7],
       [    9,   888,     1,     6,     7],
       [    9,     0,     4,     2,     2],
       [    9,     8,     6,     9,     5],
       [    0,     1,     9,     7,     4]])

In [95]:
m = np.random.randint(10, size=(5, 5))
m

array([[3, 5, 1, 7, 2],
       [9, 8, 1, 5, 5],
       [7, 4, 4, 6, 9],
       [6, 4, 3, 1, 1],
       [9, 3, 5, 7, 8]])

In [96]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[3, 5],
       [9, 8],
       [7, 4]])

In [97]:
alt_b[0, 0] = 5453
alt_b

array([[5453,    5],
       [   9,    8],
       [   7,    4]])

In [98]:
m

array([[3, 5, 1, 7, 2],
       [9, 8, 1, 5, 5],
       [7, 4, 4, 6, 9],
       [6, 4, 3, 1, 1],
       [9, 3, 5, 7, 8]])

In [99]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [100]:
v[1]

3

In [101]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [102]:
alt_getir = [1, 3, 5]

In [103]:
v[alt_getir]

array([ 3,  9, 15])

In [105]:
m = np.arange(9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
satir = np.array([0, 1])
sütun = np.array([1, 2])

In [108]:
m[satir, sütun]

array([1, 5])

In [109]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
m[0, [1, 2]]

array([1, 2])

In [111]:
m[0:, [1, 2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [112]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [113]:
v > 5

array([False, False, False, False, False])

In [114]:
v < 3

array([ True,  True, False, False, False])

In [115]:
v[v < 3]

array([1, 2])

In [116]:
v

array([1, 2, 3, 4, 5])

In [118]:
# ufunc

In [119]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)